In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib.axes as ax

In [ ]:
df=pd.read_csv("seeds_dataset.csv")

In [ ]:
df=df[:1000]

In [ ]:
df=df.drop("Unnamed: 0",axis=1)
df.head(10)


area  perimeter  compactness  ...  asymmetry  length_kernel_groove  kernel
0  15.26      14.84       0.8710  ...      2.221                 5.220       1
1  14.88      14.57       0.8811  ...      1.018                 4.956       1
2  14.29      14.09       0.9050  ...      2.699                 4.825       1
3  13.84      13.94       0.8955  ...      2.259                 4.805       1
4  16.14      14.99       0.9034  ...      1.355                 5.175       1
5  14.38      14.21       0.8951  ...      2.462                 4.956       1
6  14.69      14.49       0.8799  ...      3.586                 5.219       1
7  14.11      14.10       0.8911  ...      2.700                 5.000       1
8  16.63      15.46       0.8747  ...      2.040                 5.877       1
9  16.44      15.25       0.8880  ...      1.969                 5.533       1

[10 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   area                  210 non-null    float64
 1   perimeter             210 non-null    float64
 2   compactness           210 non-null    float64
 3   length                210 non-null    float64
 4   width                 210 non-null    float64
 5   asymmetry             210 non-null    float64
 6   length_kernel_groove  210 non-null    float64
 7   kernel                210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [ ]:
df['kernel']=df['kernel']-1


In [ ]:
df['kernel'].value_counts()

2    70
1    70
0    70
Name: kernel, dtype: int64

In [ ]:
df['kernel'].unique()

array([0, 1, 2])

In [ ]:
x=df.drop(df.columns[[7]],axis=1)
y=df['kernel']

In [ ]:
x.head()

area  perimeter  compactness  ...  width  asymmetry  length_kernel_groove
0  15.26      14.84       0.8710  ...  3.312      2.221                 5.220
1  14.88      14.57       0.8811  ...  3.333      1.018                 4.956
2  14.29      14.09       0.9050  ...  3.337      2.699                 4.825
3  13.84      13.94       0.8955  ...  3.379      2.259                 4.805
4  16.14      14.99       0.9034  ...  3.562      1.355                 5.175

[5 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.35,random_state=2)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.fit_transform(xtest)


In [ ]:
xtrain

array([[-3.20143527e-01, -3.55381019e-01,  4.36839865e-01,
        -4.94370474e-01, -1.71120059e-01, -1.43991720e+00,
        -8.92980831e-01],
       [ 5.52795640e-01,  6.16037722e-01,  2.28695945e-01,
         8.71279385e-01,  5.10777233e-01, -1.20955159e+00,
         8.78793076e-01],
       [-1.14943573e+00, -9.90539427e-01, -2.10336552e+00,
        -6.60913139e-01, -1.50908520e+00,  2.32551375e-01,
        -5.26895126e-01],
       [ 1.25450443e+00,  1.27361349e+00,  4.96309556e-01,
         1.23989382e+00,  1.07644203e+00, -1.10399707e+00,
         1.32375913e+00],
       [ 1.71783368e+00,  1.75932286e+00,  2.24448110e-01,
         2.04373975e+00,  1.33731941e+00, -1.27017412e+00,
         2.03570481e+00],
       [ 1.00605251e+00,  9.07463344e-01,  1.27366338e+00,
         7.06957288e-01,  1.08419087e+00, -1.05478584e+00,
         9.63741141e-01],
       [-1.47510919e+00, -1.66306009e+00, -1.91839729e-01,
        -1.69125710e+00, -1.24045899e+00,  8.83708649e-01,
        -1.3116534

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

classifier=KNeighborsClassifier(n_neighbors=5,p=2)
##eucledian , 1-man 

classifier.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
ypred=classifier.predict(xtest)

In [ ]:
from sklearn .metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(ytest,ypred)


In [ ]:
cm

array([[26,  1,  0],
       [ 1, 19,  0],
       [ 0,  0, 27]])

In [ ]:
accuracy_score(ytest,ypred)

0.972972972972973